core/urls.py
from django.contrib.auth.views import LogoutView, LoginView
from django.urls import path

from core import views

handler404 = views.custom_handler404
handler500 = views.custom_handler500

urlpatterns = [
    path('', views.MainView.as_view(), name='main'),
    path('search/', views.SearchView.as_view(), name='search'),

    path('vacancies/', views.VacanciesList.as_view(), name='vacancies'),
    path('vacancies/cat/<str:code>', views.VacanciesBySpecialties.as_view(), name='vacancies_by_specialties'),
    path('vacancies/<int:pk>', views.VacancyDetail.as_view(), name='vacancy_detail'),

    path('companies/', views.CompaniesList.as_view(), name='companies'),
    path('companies/<int:pk>', views.CompanyDetail.as_view(), name='company_detail'),

    path('resumes/', views.ResumesList.as_view(), name='resumes'),
    path('resumes/<int:pk>', views.ResumeDetail.as_view(), name='resume_detail'),

    path('mycompany/', views.MyCompanyView.as_view(), name='my_company'),
    path('mycompany/letsstart', views.MyCompanyStartView.as_view(), name='lets_start'),
    path('mycompany/create', views.MyCompanyCreateView.as_view(), name='create_company'),

    path('mycompany/vacancies', views.MyVacanciesView.as_view(), name='my_vacancies'),
    path('mycompany/vacancies/<int:pk>', views.MyVacancyView.as_view(), name='my_vacancy'),
    path('mycompany/vacancies/create', views.CreateVacancyView.as_view(), name='create_vacancy'),

    path('myresume/', views.MyResumeView.as_view(), name='my_resume'),
    path('myresume/letsstart', views.MyResumeStartView.as_view(), name='lets_start_resume'),
    path('myresume/create', views.CreateResumeView.as_view(), name='create_resume'),

    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', views.MySignupView.as_view(),  name='register'),
]

core/models.py
from django.contrib.auth import get_user_model
from django.core.validators import RegexValidator
from django.db import models


User = get_user_model()


class Vacancy(models.Model):
    title = models.CharField(
        'Название вакансии',
        max_length=50
    )
    specialty = models.ForeignKey(
        'Specialty',
        on_delete=models.CASCADE,
        related_name='vacancies',
        verbose_name='Специальность',
    )
    company = models.ForeignKey(
        'Company',
        on_delete=models.CASCADE,
        related_name='vacancies',
        verbose_name='Компания'
    )
    skills = models.CharField(
        'Навыки',
        max_length=255
    )
    description = models.TextField('Текст')
    salary_min = models.PositiveIntegerField('Зарплата от')
    salary_max = models.PositiveIntegerField('Зарплата до')
    published_at = models.DateTimeField(
        'Опубликованно',
        auto_now_add=True
    )

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-published_at']


class Company(models.Model):
    name = models.CharField(
        'Название компании',
        max_length=50
    )
    location = models.CharField(
        'Город',
        max_length=50
    )
    logo = models.ImageField(
        'Логотип',
        upload_to='company_images',
        default='https://place-hold.it/100x60',
    )
    description = models.TextField('Информация о компании')
    employee_count = models.PositiveSmallIntegerField('Количество сотрудников')
    owner = models.OneToOneField(
        User,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        verbose_name='Владелец'
    )

    def __str__(self):
        return self.name


class Specialty(models.Model):
    code = models.SlugField(
        'Код',
        unique=True,
    )
    title = models.CharField(
        'Название специализации',
        max_length=50
    )
    picture = models.ImageField(
        'Картинка',
        upload_to='specialties_images',
        default='https://place-hold.it/100x60'
    )

    def __str__(self):
        return self.title


class Application(models.Model):
    written_username = models.CharField('Имя', max_length=50)
    phone_regex = RegexValidator(
        regex=r'^\+?1?\d{9,15}$',
        message="Телефонный номер должен быть в формате: '+999999999'"
    )
    written_phone = models.CharField(
        'Телефон ',
        validators=[phone_regex],
        max_length=17,
        blank=True,
    )
    written_cover_letter = models.TextField('Сопроводительное письмо')
    vacancy = models.ForeignKey(
        Vacancy,
        on_delete=models.CASCADE,
        related_name='applications',
        verbose_name='Вакансия'
    )
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='applications',
        verbose_name='Пользователь'
    )

    def __str__(self):
        return self.written_username


class Resume(models.Model):
    STATUS = [
        ('0', 'Не ищу работу'),
        ('1', 'Рассматриваю предложения'),
        ('2', 'Ищу работу')
    ]
    GRADE = [
        ('0', 'Стажер'),
        ('1', 'Джуниор'),
        ('2', 'Мидл'),
        ('3', 'Сеньор'),
        ('4', 'Лид')
    ]

    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        verbose_name='Пользователь'
    )
    name = models.CharField('Имя', max_length=50)
    surname = models.CharField('Фамилия', max_length=50)
    status = models.CharField(
        'Статус',
        choices=STATUS,
        default=None,
        max_length=50
    )
    salary = models.PositiveIntegerField('Зарплата')
    specialty = models.ForeignKey(
        Specialty,
        on_delete=models.CASCADE,
        related_name='resume',
        verbose_name='Специальность'
    )
    grade = models.CharField(
        'Квалификация',
        choices=GRADE,
        default=None,
        max_length=50
    )
    photo = models.ImageField(
        'Фотография',
        upload_to='user_images',
        default='https://place-hold.it/100x60',
    )
    education = models.CharField('Образование', max_length=100)
    experience = models.TextField('Опыт работы', null=True)
    description = models.TextField('О себе', null=True)
    portfolio = models.CharField('Портфолио', max_length=100)
    phone = RegexValidator(
        regex=r'^\+?1?\d{9,15}$',
        message="Телефонный номер должен быть в формате: '+999999999'"
    )
    phone = models.CharField(
        'Телефон ',
        validators=[phone],
        max_length=17,
        blank=True
    )

    def __str__(self):
        return f'{self.name} {self.surname}'

    class Meta:
        ordering = ['-pk']

core/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.db.models import Count, Q
from django.http import HttpResponseBadRequest, HttpResponseServerError
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse_lazy
from django.views.generic import TemplateView, ListView, DetailView, CreateView, UpdateView

from core.forms import SignupForm, ApplicationForm, CompanyForm, VacancyForm, ResumeForm
from core.models import Specialty, Company, Vacancy, Resume, Application

User = get_user_model()


class MainView(TemplateView):
    """Вывод главной страницы."""

    template_name = 'core/index.html'

    def get_context_data(self, **kwargs):
        specialties = Specialty.objects.all().annotate(vacancy_count=Count('vacancies'))
        companies = Company.objects.all().annotate(vacancy_count=Count('vacancies'))[:8]

        vacancy = Vacancy.objects.first()
        examples_for_search = vacancy.skills.split(', ')[:4]

        return {
            'specialties': specialties,
            'companies': companies,
            'examples': examples_for_search,
        }


class VacanciesList(ListView):
    """Вывод страницы со списком всех вакансий."""

    model = Vacancy
    template_name = 'core/vacancies.html'
    queryset = Vacancy.objects.select_related('specialty', 'company')
    context_object_name = 'vacancies'


class VacanciesBySpecialties(ListView):
    """Вывод страницы со списком вакансий по категориям."""

    model = Vacancy
    template_name = 'core/vacancies.html'
    context_object_name = 'vacancies'

    def get_queryset(self):
        return Vacancy.objects.filter(
            specialty__code=self.kwargs['code']).select_related('specialty', 'company')


class VacancyDetail(LoginRequiredMixin, DetailView, CreateView):
    """Вывод страницы с полным описанием вакансии и формой для заполнения отклика."""

    template_name = 'core/vacancy.html'
    queryset = Vacancy.objects.select_related('company', 'specialty')
    context_object_name = 'vacancy'
    model = Application
    form_class = ApplicationForm
    success_url = reverse_lazy('vacancies')

    def form_valid(self, form):
        form.instance.vacancy = self.get_object()
        form.instance.user = self.request.user
        return super(VacancyDetail, self).form_valid(form)


class CompanyDetail(LoginRequiredMixin, DetailView):
    """Вывод страницы описания компании."""

    template_name = 'core/company.html'
    model = Company
    context_object_name = 'company'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['vacancies'] = self.object.vacancies.select_related(
            'specialty', 'company'
        )
        return context


class CreateCompanyRequiredMixin:
    """Пользовательский класс-миксин. Перенаправляет пользователя без компании
    на страницу с предложением создать компанию."""

    def dispatch(self, request, *args, **kwargs):
        try:
            company = request.user.company
            return super().dispatch(request, *args, **kwargs)
        except Company.DoesNotExist:
            return redirect('lets_start')


class MyCompanyStartView(LoginRequiredMixin, TemplateView):
    """Вывод страницы с предложением создать компанию. В том случае, если пользователь
    попал на эту страницу и у него есть своя компания, перенаправляем его на страницу
    с редактированием данных о компании."""

    template_name = 'core/company-create.html'

    def get(self, request, *args, **kwargs):
        try:
            company = request.user.company
            return redirect('my_company')
        except Company.DoesNotExist:
            return render(request, self.template_name)


class MyCompanyCreateView(
    LoginRequiredMixin,
    SuccessMessageMixin,
    CreateView
):
    """Вывод страницы для создания компании пользователя."""

    model = Company
    form_class = CompanyForm
    template_name = 'core/company-edit.html'
    success_url = reverse_lazy('my_company')
    success_message = 'Компания создана.'

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super(MyCompanyCreateView, self).form_valid(form)


class MyCompanyView(
    LoginRequiredMixin,
    CreateCompanyRequiredMixin,
    SuccessMessageMixin,
    UpdateView
):
    """Вывод страницы с данными о компании пользователя и возможностью редактировать ее."""

    template_name = 'core/company-edit.html'
    model = Company
    form_class = CompanyForm
    success_message = 'Данные обновлены.'

    def get_object(self, queryset=None):
        return self.request.user.company

    def get_success_url(self):
        return self.request.path

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['logo'] = self.object.logo
        return context


class MyVacanciesView(LoginRequiredMixin, CreateCompanyRequiredMixin, ListView):
    """Вывод страницы со списком вакансий, созданные пользователем."""

    template_name = 'core/vacancy-list.html'
    model = Vacancy
    context_object_name = 'vacancies'

    def get_queryset(self):
        return Vacancy.objects.prefetch_related(
                'applications').filter(company=self.request.user.company)


class MyVacancyView(LoginRequiredMixin, CreateCompanyRequiredMixin, UpdateView):

    model = Vacancy
    template_name = 'core/vacancy-edit.html'
    form_class = VacancyForm
    context_object_name = 'vacancy'

    def get_object(self, queryset=None):
        return get_object_or_404(
                    Vacancy.objects.prefetch_related('applications'),
                    company=self.request.user.company, pk=self.kwargs['pk']
                )

    def get_success_url(self):
        return self.request.path

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['applications'] = self.object.applications.all()
        return context

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super(MyVacancyView, self).form_valid(form)


class CreateVacancyView(
    LoginRequiredMixin,
    CreateCompanyRequiredMixin,
    SuccessMessageMixin,
    CreateView
):
    """Вывод страницы с формой для создания вакансии."""

    model = Vacancy
    form_class = VacancyForm
    template_name = 'core/vacancy-create.html'
    success_url = reverse_lazy('my_vacancies')
    success_message = 'Вакансия создана.'

    def form_valid(self, form):
        form.instance.company = self.request.user.company
        return super(CreateVacancyView, self).form_valid(form)


class MySignupView(SuccessMessageMixin, CreateView):
    """Вывод страницы для регистрации на сайте."""

    template_name = 'registration/register.html'
    success_url = reverse_lazy('login')
    form_class = SignupForm
    success_message = 'Аккаунт создан.'


class CreateResumeRequiredMixin:
    """Пользовательский класс-миксин. Перенаправляет пользователя без резюме
    на страницу с предложением создать резюме."""

    def dispatch(self, request, *args, **kwargs):
        try:
            resume = request.user.resume
            return super().dispatch(request, *args, **kwargs)
        except Resume.DoesNotExist:
            return redirect('lets_start_resume')


class MyResumeStartView(LoginRequiredMixin, TemplateView):
    """Вывод страницы с предложением создать резюме. В том случае, если пользователь
    попал на эту страницу и у него есть свое резюме, перенаправляем его на страницу
    с редактированием данных о резюме."""

    template_name = 'core/resume-create.html'

    def get(self, request, *args, **kwargs):
        try:
            resume = request.user.resume
            return redirect('my_resume')
        except Resume.DoesNotExist:
            return render(request, self.template_name)


class MyResumeView(
    LoginRequiredMixin,
    CreateResumeRequiredMixin,
    SuccessMessageMixin,
    UpdateView
):
    """Вывод страницы с данными о резюме пользователя и возможностью редактировать ее."""

    model = Resume
    template_name = 'core/resume-edit.html'
    form_class = ResumeForm
    context_object_name = 'resume'
    success_message = 'Данные обновлены.'

    def get_object(self, queryset=None):
        return Resume.objects.select_related('user', 'specialty').get(
                    user=self.request.user
                )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['photo'] = self.object.photo
        return context

    def get_success_url(self):
        return self.request.path


class CreateResumeView(
    LoginRequiredMixin,
    SuccessMessageMixin,
    CreateView
):
    """Вывод страницы для создания резюме пользователя."""

    model = Resume
    form_class = ResumeForm
    template_name = 'core/resume-edit.html'
    success_url = reverse_lazy('my_resume')
    success_message = 'Резюме создано.'

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(CreateResumeView, self).form_valid(form)


class SearchView(ListView):
    """Вывод страницы с поиском по вакансиям."""

    model = Vacancy
    template_name = 'core/search.html'
    context_object_name = 'vacancies'

    def get_queryset(self):
        search_query = self.request.GET.get('q')
        if search_query:
            vacancies = Vacancy.objects.select_related(
                'specialty', 'company'
            ).filter(Q(skills__icontains=search_query) | Q(title__icontains=search_query))
        else:
            vacancies = Vacancy.objects.select_related(
                'specialty', 'company'
            ).all()
        return vacancies

    def get_context_data(self, *, object_list=None, **kwargs):

templates/core/companies.html
{% extends 'base.html' %}
{% block title %}Вакансии : {{ block.super }}{% endblock %}
{% block content %}
{% load user_tags %}
<main class="container mt-3">
    <section>
        <h1 class="h1 text-center mx-auto mt-4 pt-5" style="font-size: 70px;"><strong>Компании</strong></h1>
        <p class="text-center pt-1">{{ companies.count }} компаний</p>
        <div class="row mt-5">
            <div class="col-12 col-lg-8 offset-lg-2 m-auto">
                {% for company in companies %}
                <div class="card mb-4">
                    <div class="card-body px-4">
                        <div class="row">
                            <div class="col-12 col-md-8 col-lg-9">
                                <h2 class="h2 pb-2">
                                        <a href="{% url 'company_detail' company.id %}">{{ company.name }}</a>
                                </h2>

                                <p class="mb-2">{{ company.location }} • {{ company.vacancy_count }} открытых вакансий</p>
                                <p class="text-muted pt-1">{{ company.description|truncatewords:20 }}</p>
                            </div>
                            <div class="col-12 col-md-4 col-lg-3 d-flex align-items-end">
                                <a href="{% url 'company_detail' company.id %}"><img
                                        src="{{ company.logo.url }}" width="130" height="80" alt=""></a>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </section>
</main>
{% endblock %}

templates/core/company-edit.html
{% extends 'base.html' %}
{% block title %}Моя компания : {{ block.super }}{% endblock %}
{% block content %}
<!--suppress ALL -->
<main class="container mt-3 pb-5">
    <div class="row mt-5">
        <div class="col-12 col-lg-4">
            <aside class="pt-3 pb-4 px-4 mb-5 card">
                <h1 class="h4 pt-2 pb-2">Моя компания</h1>
                <div class="nav flex-column nav-pills">
                    <a class="nav-link active" href="{% url 'my_company' %}">1. Информация о&nbsp;компании</a>
                    <a class="nav-link" href="{% url 'my_vacancies' %}">2. Вакансии</a>
                </div>
            </aside>
        </div>
        <div class="col-12 col-lg-8">
            <div class="card">
                <div class="card-body px-4 pb-4">
                    <!-- Tab -->
                    <section class="tab-pane fade show active">
                        <h2 class="h4 pt-2 pb-3">Информация о&nbsp;компании</h2>

                        {% if request.path == '/mycompany/create' %}
                        <form action="{% url 'create_company' %}" method="post" enctype="multipart/form-data">
                        {% else %}
                        <form action="{% url 'my_company' %}" method="post" enctype="multipart/form-data">
                        {% endif %}
                                {% csrf_token %}

                                <div class="row">
                                    <div class="col-12 col-md-6">
                                        <div class="form-group pb-2">
                                            <label class="mb-2 text-dark" for="companyName">Название компании</label>
                                            {{ form.name }}
                                        </div>
                                    </div>
                                    <div class="col-12 col-md-6">
                                        <div class="form-group">
                                            <label class="mb-2 text-dark" for="companyLogo">Логотип</label>
                                            <div class="row align-items-center">
                                                <div class="col-6">
                                                    <img src="{{ logo.url }}" alt=""
                                                         style="max-width: 120px;height: auto;">
                                                </div>
                                                <div class="col-6" style="position: relative;">
                                                    <div class="input-group-prepend"
                                                         style="position: absolute; top: 0;right: 15px;">
                                                        <span class="btn btn-info px-4">Загрузить</span><br>
                                                    </div>
                                                    <div class="custom-file" style="">
                                                        {{ form.logo }}
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-12 col-md-6">
                                        <div class="form-group pb-2">
                                            <!--suppress XmlInvalidId -->
                                            <label class="mb-2 text-dark" for="companyTeam">Количество человек в
                                                компании</label>
                                            {{ form.employee_count }}
                                        </div>
                                    </div>
                                    <div class="col-12 col-md-6">
                                        <div class="form-group pb-2">
                                            <label class="mb-2 text-dark" for="companyLocation">География</label>
                                            {{ form.location }}
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group pb-2">
                                    <label class="mb-2 text-dark" for="companyInfo">Информация о&nbsp;компании</label>
                                    {{ form.description }}
                                </div>
                                <div class="form-group">
                                    <input type="submit" class="btn btn-info" value="Сохранить">
                                </div>
                            </form>
                    </section>
                    <!-- END Tab -->
                </div>
            </div>
        </div>
    </div>
</main>
{% endblock %}

templates/core/company.html
{% extends 'base.html' %}
{% block title %}{{ company.name }} : {{ block.super }}{% endblock %}
{% block content %}
{% load user_tags %}
<main class="container mt-3">
    <div class="navbar mt-5">
        <p><a href="{{ request.META.HTTP_REFERER }}">Назад</a></p>
    </div>
    <section>
        <div class="text-center">
            <img src="{{ company.logo.url }}" width="130" height="80" alt="">
        </div>
        <h1 class="h1 text-center mx-auto mt-0 pt-1" style="font-size: 70px;"><strong>{{ company.name }}</strong></h1>
        <p class="text-center pt-1">Компания, {{ company.location }}, {{ vacancies.count }} вакансий</p>
        <p class="text-center">{{ company.description }}</p>
        <div class="row mt-5">
            <div class="col-12 col-lg-8 offset-lg-2 m-auto">
                {% for vacancy in vacancies %}
                <div class="card mb-4">
                    <div class="card-body px-4">
                        <div class="row">
                            <div class="col-12 col-md-8 col-lg-9">
                                <h2 class="h2 pb-2">
                                    <a href="{% url 'vacancy_detail' vacancy.id %}">
                                        {{ vacancy.title }}
                                    </a>
                                </h2>
                                <p class="mb-2">{{ vacancy.specialty.title }} • {{ vacancy.skills|replace }}</p>
                                <p>От {{ vacancy.salary_min|convert_digit }} до {{ vacancy.salary_max|convert_digit }} руб.</p>
                                <p class="text-muted pt-1">{{ vacancy.published_at }}</p>
                            </div>
                            <div class="col-12 col-md-4 col-lg-3 d-flex align-items-end">
                                <a href="{% url 'vacancy_detail' vacancy.id %}">
                                <img src="{{ company.logo.url }}" width="130" height="80" alt=""></a>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </section>
</main>
{% endblock %}

templates/core/index.html
{% extends 'base.html' %}
{% block title %}Главная : {{ block.super }}{% endblock %}
{% block content %}
{% load static %}
<main class="container mt-3">
    <section>
        <h1 class="h1 text-center mx-auto mt-4 py-5"><strong>Вакансии для <br>разработчиков</strong></h1>
        <div class="row">
            <div class="col-12 col-md-8 col-lg-6 offset-lg-3 offset-md-2">
                <form class="form-inline mb-3" enctype="multipart/form-data" method="get" action="{% url 'search' %}">
                    <div class="form-group col-8 col-md-10 pl-0">
                        <input class="form-control w-100" type="search" placeholder="Найти работу или стажировку" aria-label="Найти работу или стажировку"  name="q" value="{{ request.GET.q }}">
                    </div>
                    <div class="form-group col-4 col-md-2 pl-0">
                        <button class="btn btn-primary w-100" type="submit">Найти</button>
                    </div>
                </form>
                <p>Например:
                    {% for example in examples %}
                    <a href="{% url 'search' %}?q={{ example }}" class="text-dark border-bottom border-dark m-1 text-decoration-none">{{ example }}</a>
                    {% endfor %}
                </p>
            </div>
        </div>
    </section>

    <section class="mt-5 pt-3">
        <h2 class="h2 font-weight-normal text-center mb-5">Вакансии по рубрикам</h2>
        <div class="row mb-0">
            {% for specialty in specialties %}
            <div class="col-6 col-md-6 col-lg-3">
                <div class="card pt-4 text-center mb-4">
                    <img class="mx-auto d-block" src="{{specialty.picture.url}}" width="80" height="80" alt="">
                    <div class="card-body">
                        <p class="card-text mb-2">{{ specialty.title }}</p>
                        <p class="card-text"><a href="{% url 'vacancies_by_specialties' specialty.code %}">{{ specialty.vacancy_count }} вакансий</a></p>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </section>

    <section class="my-5 pt-3">
        <h2 class="h2 font-weight-normal text-center mb-5">Нам доверяют лучшие компании</h2>
        <div class="row mb-0">
            {% for company in companies %}
            <div class="col-6 col-md-6 col-lg-3">
                <div class="card pt-4 text-center mb-4">
                    <a href="#" style="max-width: 150px;" class="mx-auto d-block">
                        <img class="mx-auto d-block mw-100" src="{{ company.logo.url }}" alt="">
                    </a>
                    <div class="card-body">
                        <p class="card-text"><a href="{% url 'company_detail' company.id %}">{{ company.vacancy_count }} вакансий</a></p>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </section>
</main>
{% endblock %}

templates/core/login.html
{% extends 'base.html' %}
{% block title %}Вход : {{ block.super }}{% endblock %}
{% block content %}
{% load crispy_forms_tags %}
<main class="container">
    <div class="row">
        <div class="col-8 col-lg-4 offset-2 offset-lg-4">
            <div class="text-center mt-5 b-1">
                <h1 class="h3 mb-3 font-weight-normal">Джуманджи</h1>
                <p class="h5 font-weight-light">Войдите, чтобы управлять</p>
            </div>
            {% crispy form "bootstrap4" %}
            <div class="mt-4 text-center"><p>Нет аккаунта? <a href="{% url 'register' %}">Зарегистрируйтесь!</a></p>
            </div>
        </div>
    </div>
</main>
{% endblock %}

templates/core/resume-create.html
{% extends 'base.html' %}
{% block title %}{{ block.super }}{% endblock %}
{% block content %}
<main class="container mt-3 pb-5">
    <section class="col-12 col-lg-6 offset-lg-3 mt-5 card">
        <div class="card-body px-3 pb-4">
            <h1 class="h4 pt-2">Мое резюме</h1>
            <p class="mt-2">У вас нет резюме. Хотите создать его?</p>
            <a href="{% url 'create_resume' %}" class="btn btn-info mb-2">Создать резюме</a>
        </div>
    </section>
</main>
{% endblock %}

templates/core/resumes.html
{% extends 'base.html' %}
{% block title %}Вакансии : {{ block.super }}{% endblock %}
{% block content %}
{% load user_tags %}
<main class="container mt-3">
    <section>
        <h1 class="h1 text-center mx-auto mt-4 pt-5" style="font-size: 70px;"><strong>Резюме</strong></h1>
        <p class="text-center pt-1">{{ resumes.count }} резюме</p>
        <div class="row mt-5">
            <div class="col-12 col-lg-8 offset-lg-2 m-auto">
                {% for resume in resumes %}
                <div class="card mb-4">
                    <div class="card-body px-4">
                        <div class="row">
                            <div class="col-12 col-md-8 col-lg-9">
                                <h2 class="h2 pb-2">
                                    <a href="{% url 'resume_detail' resume.id %}">
                                        {{ resume.name }} {{ resume.surname }}
                                    </a>
                                </h2>
                                <p class="mb-2">{{ resume.get_grade_display }} • {{ resume.specialty }} • {{ resume.get_status_display }}</p>
                                <p>Ожидаемая заработная плата: {{ resume.salary }} руб.</p>
                                <p class="text-muted pt-1">{{ resume.experience|truncatewords:20 }}</p>
                            </div>
                            <div class="col-12 col-md-4 col-lg-3 d-flex align-items-end">
                                <a href="{% url 'resume_detail' resume.id %}"><img src="{{ resume.photo.url }}" width="130" height="80" alt=""></a>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </section>
</main>
{% endblock %}